language: php

php:
  - 5.6.28
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

sudo: false

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -d memory_limit=1024M --coverage-text
