language: php

os:
  - linux

dist:
  - bionic
  - xenial

arch: amd64

jobs:
  include:
    - php: 8.1.0
      dist: bionic
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit -d memory_limit=1024M --coverage-text


